#pragma once
#include "AftrConfig.h"

#ifdef AFTR_CONFIG_USE_OCULUS_RIFT_DK2

#include "./OculusSDK/LibOVR/Include/OVR.h"
#include "./OculusSDK/LibOVR/Include/OVR_Version.h"
#include "./OculusSDK/LibOVR/Include/OVR_Kernel.h"

//#include "./OculusSDK/LibOVR/Include/OVR.h"
//#include "./OculusSDK/LibOVR/Include/OVRVersion.h"
//#include "./OculusSDK/LibOVR/Src/OVR_Device.h"
//#include "./OculusSDK/LibOVR/Src/OVR_DeviceConstants.h"
//#include "./OculusSDK/LibOVR/Src/OVR_DeviceHandle.h"
//#include "./OculusSDK/LibOVR/Src/OVR_DeviceImpl.h"
//#include "./OculusSDK/LibOVR/Src/OVR_DeviceMessages.h"
//#include "./OculusSDK/LibOVR/Src/OVR_HIDDevice.h"
//#include "./OculusSDK/LibOVR/Src/OVR_HIDDeviceBase.h"
//#include "./OculusSDK/LibOVR/Src/OVR_HIDDeviceImpl.h"
//#include "./OculusSDK/LibOVR/Src/OVR_JSON.h"
//#include "./OculusSDK/LibOVR/Src/OVR_LatencyTestImpl.h"
//
////#include "./OculusSDK/LibOVR/Src/OVR_Linux_DeviceManager.h"
////#include "./OculusSDK/LibOVR/Src/OVR_Linux_HIDDevice.h"
////#include "./OculusSDK/LibOVR/Src/OVR_Linux_HMDDevice.h"
////#include "./OculusSDK/LibOVR/Src/OVR_OSX_DeviceManager.h"
////#include "./OculusSDK/LibOVR/Src/OVR_OSX_HIDDevice.h"
////#include "./OculusSDK/LibOVR/Src/OVR_OSX_HMDDevice.h"
//
//#include "./OculusSDK/LibOVR/Src/OVR_Profile.h"
//#include "./OculusSDK/LibOVR/Src/OVR_SensorFilter.h"
//#include "./OculusSDK/LibOVR/Src/OVR_SensorFusion.h"
//#include "./OculusSDK/LibOVR/Src/OVR_SensorImpl.h"
//#include "./OculusSDK/LibOVR/Src/OVR_ThreadCommandQueue.h"
//#include "./OculusSDK/LibOVR/Src/OVR_Win32_DeviceManager.h"
//#include "./OculusSDK/LibOVR/Src/OVR_Win32_DeviceStatus.h"
//#include "./OculusSDK/LibOVR/Src/OVR_Win32_HIDDevice.h"
//#include "./OculusSDK/LibOVR/Src/OVR_Win32_HMDDevice.h"
//#include "./OculusSDK/LibOVR/Src/OVR_Win32_SensorDevice.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_Alg.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_Allocator.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_Array.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_Atomic.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_Color.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_ContainerAllocator.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_File.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_Hash.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_KeyCodes.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_List.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_Log.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_Math.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_RefCount.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_Std.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_String.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_StringHash.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_SysFile.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_System.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_Threads.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_Timer.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_Types.h"
//#include "./OculusSDK/LibOVR/Src/Kernel\OVR_UTF8Util.h"
//#include "./OculusSDK/LibOVR/Src/Util\Util_LatencyTest.h"
//#include "./OculusSDK/LibOVR/Src/Util\Util_Render_Stereo.h"

#endif